openapi: 3.1.0
info:
  version: '1.0.0'
  title: 'OpenAPI BUG REST API'
servers:
  - url: 'localhost:3000'

paths:
  /api/v1/third:
    get:
      tags: [ custom-api-third ]
      operationId: "thirdGet"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ThirdGetResponse'

components:
  schemas:
    ThirdGetResponse:
      type: object
      properties:
        name:
          type: string
        valueType:
          type: string

tags:
  - name: custom-api-third
    description: 'All API operations'